### PR TITLE
fix: expand disk to 8G for Fedora 39+ arm-minimal test. [litian]

### PR DESCRIPTION
**Pull request by litian1992**
The fix requires 1. qcow2 be expanded to 8G; 2. growpart and resize2fs in guest.

### CODE REVIEW

**Comment by henrywang** [comment]
@litian1992 Could you please squash three commits into one? Thanks.

**Comment by litian1992** [comment]
@henrywang Hi Xiaofeng, I switched to this PR. Thanks for reviewing.
https://github.com/virt-s1/rhel-edge/pull/6449

**Pull request closed without merging**
