### PR TITLE
replace containerized fdo server with fdo-aio service

### PR DESCRIPTION
**Pull request by yih-redhat**
This PR will
1. replace containerized fdo server with fdo-aio service
2. update check-ostree.yaml to check fdo onboarding status.

Already passed in my local cs9 env, and according to the test result in upstream, it should pass on all platforms.

### CODE REVIEW

**Comment by henrywang** [comment]
@yih-redhat We can't test on RHEL 9.1 and CS9 because two blocker bugs. We have to leave this PR here until blocker bugs got fix. After that we can fully test this PR. Thanks.

**Comment by yih-redhat** [comment]
> @yih-redhat We can't test on RHEL 9.1 and CS9 because two blocker bugs. We have to leave this PR here until blocker bugs got fix. After that we can fully test this PR. Thanks.

Yeah, let's wait for those blockers get fixed.

**Comment by henrywang** [comment]
@yih-redhat Could you please rebase this PR, RHEL 9.1 blocker bug has been fixed already. Thanks.

**Pull request closed without merging**
