### PR TITLE
test fdo packages

### PR DESCRIPTION
**Pull request by yih-redhat**
This PR includes:
1. Install FDO packages and start FDO servers in ostree-simplified-installer.sh

For FDO container test, will test it and make another pr

### CODE REVIEW

**Comment by yih-redhat** [comment]
Failed due to bug https://bugzilla.redhat.com/show_bug.cgi?id=2170903

**Comment by henrywang** [comment]
@yih-redhat Could you please make main rebase? I fixed some issues in PR https://github.com/virt-s1/rhel-edge/pull/2132, https://github.com/virt-s1/rhel-edge/pull/2135, and https://github.com/virt-s1/rhel-edge/pull/2124. Thanks!
And the bug has a work around https://bugzilla.redhat.com/show_bug.cgi?id=2170903#c1

**Comment by yih-redhat** [comment]
> @yih-redhat Could you please make main rebase? I fixed some issues in PR #2132, #2135, and #2124. Thanks! And the bug has a work around https://bugzilla.redhat.com/show_bug.cgi?id=2170903#c1

sure, I may need to add one more test "onboarding user", and I will make a rebase and push later.

**Pull request closed without merging**
