### PR TITLE
ci: temporarily disable Fedora Rawhide update F40 and disable F38

### PR DESCRIPTION
**Pull request by mcattamoredhat**
Let's disable temporarily Fedora Rawhide in our CI until osbuild-composer supports F41.

In addition, let's disable F38 tests and update F38/F40 urls.

### CODE REVIEW

**Comment by henrywang** [comment]
Could you please fix shellcheck and yamlint error? Thanks.

**Comment by henrywang** [comment]
@mcattamoredhat I think we can keep fedora 40, just remove fedora 38 and disable fedora rawhide.

**Review by yih-redhat — COMMENTED** [review]
LGTM, thanks Mario.

**Review by henrywang — APPROVED** [review]
Thanks @mcattamoredhat !

**Pull request merged**
