### PR TITLE
Check sos package has been included in the edge commit package set

### PR DESCRIPTION
**Pull request by mcattamoredhat**
This PR includes a playbook task that executes the sos report and make sure command execution has been successful.

Needs osbuild-composer v74.

### CODE REVIEW

**Comment by henrywang** [comment]
Thanks for doing this. LGTM. Only one suggestion. Can we check sos in all image type tests? I mean add `-e sos_package="${SOS_PACKAGE}" into all image type test script. Thanks.

**Comment by mcattamoredhat** [comment]
> Thanks for doing this. LGTM. Only one suggestion. Can we check sos in all image type tests? I mean add `-e sos_package="${SOS_PACKAGE}" into all image type test script. Thanks.

Sure no problem. Later on, I think we need to confirm if the sos package in upstream code is being included in all image types or just in edge commit package set.

**Comment by henrywang** [comment]
@mcattamoredhat Could you please make `main` rebase? I fixed some issues in PR https://github.com/virt-s1/rhel-edge/pull/2132, https://github.com/virt-s1/rhel-edge/pull/2135, and https://github.com/virt-s1/rhel-edge/pull/2124. Thanks!

**Review by henrywang — APPROVED** [review]
LGTM. I think we can land this PR. The failure is not caused by this PR. Thanks for doing this @mcattamoredhat.

**Pull request merged**
